// Code generated by internal/tools/entitymodel/generate. DO NOT EDIT.
package datasetapi

const (
	stagePlanned  LifecycleStage = "planned"
	stageLarva    LifecycleStage = "embryo_larva"
	stageJuvenile LifecycleStage = "juvenile"
	stageAdult    LifecycleStage = "adult"
	stageRetired  LifecycleStage = "retired"
	stageDeceased LifecycleStage = "deceased"
)

const (
	housingStateQuarantine     HousingState = "quarantine"
	housingStateActive         HousingState = "active"
	housingStateCleaning       HousingState = "cleaning"
	housingStateDecommissioned HousingState = "decommissioned"
)

const (
	environmentTypeAquatic     = "aquatic"
	environmentTypeTerrestrial = "terrestrial"
	environmentTypeArboreal    = "arboreal"
	environmentTypeHumid       = "humid"
)

const (
	datasetProtocolStatusDraft     = "draft"
	datasetProtocolStatusSubmitted = "submitted"
	datasetProtocolStatusApproved  = "approved"
	datasetProtocolStatusOnHold    = "on_hold"
	datasetProtocolStatusExpired   = "expired"
	datasetProtocolStatusArchived  = "archived"
)

const (
	datasetPermitStatusDraft     = "draft"
	datasetPermitStatusSubmitted = "submitted"
	datasetPermitStatusApproved  = "approved"
	datasetPermitStatusOnHold    = "on_hold"
	datasetPermitStatusExpired   = "expired"
	datasetPermitStatusArchived  = "archived"
)

const (
	datasetSampleStatusStored    = "stored"
	datasetSampleStatusInTransit = "in_transit"
	datasetSampleStatusConsumed  = "consumed"
	datasetSampleStatusDisposed  = "disposed"
)

const (
	datasetTreatmentStatusPlanned    = "planned"
	datasetTreatmentStatusInProgress = "in_progress"
	datasetTreatmentStatusCompleted  = "completed"
	datasetTreatmentStatusFlagged    = "flagged"
)

const (
	procedureStatusScheduled  = "scheduled"
	procedureStatusInProgress = "in_progress"
	procedureStatusCompleted  = "completed"
	procedureStatusCancelled  = "cancelled"
	procedureStatusFailed     = "failed"
)
