# Markdownlint rules for docs linting.
# TODO(owner: Core Maintainers, target: 2026-03-01, issue: #116): fold into unified lint policy.
# Context (#114): keep doc lint rules aligned with lint toolchain adjustments.
default: true

MD013:
  line_length: 120
  code_blocks: false
  tables: false

MD033: false
MD041: false
