-- Code generated by internal/tools/entitymodel/generate. DO NOT EDIT.
-- Dialect: postgres

CREATE TABLE IF NOT EXISTS breeding_units (
    created_at TIMESTAMPTZ NOT NULL,
    female_ids JSONB,
    housing_id UUID,
    id UUID NOT NULL,
    line_id UUID,
    male_ids JSONB,
    name TEXT NOT NULL,
    pairing_attributes JSONB,
    pairing_intent TEXT,
    pairing_notes TEXT,
    protocol_id UUID,
    strain_id UUID,
    strategy TEXT NOT NULL,
    target_line_id UUID,
    target_strain_id UUID,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (housing_id) REFERENCES housing_units(id),
    FOREIGN KEY (line_id) REFERENCES lines(id),
    FOREIGN KEY (protocol_id) REFERENCES protocols(id),
    FOREIGN KEY (strain_id) REFERENCES strains(id),
    FOREIGN KEY (target_line_id) REFERENCES lines(id),
    FOREIGN KEY (target_strain_id) REFERENCES strains(id)
);

CREATE TABLE IF NOT EXISTS cohorts (
    created_at TIMESTAMPTZ NOT NULL,
    housing_id UUID,
    id UUID NOT NULL,
    name TEXT NOT NULL,
    project_id UUID,
    protocol_id UUID,
    purpose TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (housing_id) REFERENCES housing_units(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (protocol_id) REFERENCES protocols(id)
);

CREATE TABLE IF NOT EXISTS facilities (
    access_policy TEXT NOT NULL,
    code TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    environment_baselines JSONB,
    housing_unit_ids JSONB,
    id UUID NOT NULL,
    name TEXT NOT NULL,
    project_ids JSONB,
    updated_at TIMESTAMPTZ NOT NULL,
    zone TEXT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS genotype_markers (
    alleles JSONB NOT NULL,
    assay_method TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    id UUID NOT NULL,
    interpretation TEXT NOT NULL,
    locus TEXT NOT NULL,
    name TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version TEXT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS housing_units (
    capacity INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    environment TEXT NOT NULL,
    facility_id UUID NOT NULL,
    id UUID NOT NULL,
    name TEXT NOT NULL,
    state TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (facility_id) REFERENCES facilities(id)
);

CREATE TABLE IF NOT EXISTS lines (
    code TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    default_attributes JSONB,
    deprecated_at TIMESTAMPTZ,
    deprecation_reason TEXT,
    description TEXT,
    extension_overrides JSONB,
    genotype_marker_ids JSONB NOT NULL,
    id UUID NOT NULL,
    name TEXT NOT NULL,
    origin TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS observations (
    cohort_id UUID,
    created_at TIMESTAMPTZ NOT NULL,
    data JSONB,
    id UUID NOT NULL,
    notes TEXT,
    observer TEXT NOT NULL,
    organism_id UUID,
    procedure_id UUID,
    recorded_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (cohort_id) REFERENCES cohorts(id),
    FOREIGN KEY (organism_id) REFERENCES organisms(id),
    FOREIGN KEY (procedure_id) REFERENCES procedures(id)
);

CREATE TABLE IF NOT EXISTS organisms (
    attributes JSONB,
    cohort_id UUID,
    created_at TIMESTAMPTZ NOT NULL,
    housing_id UUID,
    id UUID NOT NULL,
    line TEXT NOT NULL,
    line_id UUID,
    name TEXT NOT NULL,
    parent_ids JSONB,
    project_id UUID,
    protocol_id UUID,
    species TEXT NOT NULL,
    stage TEXT NOT NULL,
    strain_id UUID,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (cohort_id) REFERENCES cohorts(id),
    FOREIGN KEY (housing_id) REFERENCES housing_units(id),
    FOREIGN KEY (line_id) REFERENCES lines(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (protocol_id) REFERENCES protocols(id),
    FOREIGN KEY (strain_id) REFERENCES strains(id)
);

CREATE TABLE IF NOT EXISTS permits (
    allowed_activities JSONB NOT NULL,
    authority TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    facility_ids JSONB NOT NULL,
    id UUID NOT NULL,
    notes TEXT,
    permit_number TEXT NOT NULL,
    protocol_ids JSONB NOT NULL,
    status TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    valid_from TIMESTAMPTZ NOT NULL,
    valid_until TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS procedures (
    cohort_id UUID,
    created_at TIMESTAMPTZ NOT NULL,
    id UUID NOT NULL,
    name TEXT NOT NULL,
    observation_ids JSONB,
    organism_ids JSONB,
    project_id UUID,
    protocol_id UUID NOT NULL,
    scheduled_at TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL,
    treatment_ids JSONB,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (cohort_id) REFERENCES cohorts(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (protocol_id) REFERENCES protocols(id)
);

CREATE TABLE IF NOT EXISTS projects (
    code TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    description TEXT,
    facility_ids JSONB NOT NULL,
    id UUID NOT NULL,
    organism_ids JSONB,
    procedure_ids JSONB,
    protocol_ids JSONB,
    supply_item_ids JSONB,
    title TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS protocols (
    code TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    description TEXT,
    id UUID NOT NULL,
    max_subjects INTEGER NOT NULL,
    status TEXT NOT NULL,
    title TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS samples (
    assay_type TEXT NOT NULL,
    attributes JSONB,
    chain_of_custody JSONB NOT NULL,
    cohort_id UUID,
    collected_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    facility_id UUID NOT NULL,
    id UUID NOT NULL,
    identifier TEXT NOT NULL,
    organism_id UUID,
    source_type TEXT NOT NULL,
    status TEXT NOT NULL,
    storage_location TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (cohort_id) REFERENCES cohorts(id),
    FOREIGN KEY (facility_id) REFERENCES facilities(id),
    FOREIGN KEY (organism_id) REFERENCES organisms(id)
);

CREATE TABLE IF NOT EXISTS strains (
    code TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    description TEXT,
    generation TEXT,
    genotype_marker_ids JSONB,
    id UUID NOT NULL,
    line_id UUID NOT NULL,
    name TEXT NOT NULL,
    retired_at TIMESTAMPTZ,
    retirement_reason TEXT,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (line_id) REFERENCES lines(id)
);

CREATE TABLE IF NOT EXISTS supply_items (
    attributes JSONB,
    created_at TIMESTAMPTZ NOT NULL,
    description TEXT,
    expires_at TIMESTAMPTZ,
    facility_ids JSONB NOT NULL,
    id UUID NOT NULL,
    lot_number TEXT,
    name TEXT NOT NULL,
    project_ids JSONB NOT NULL,
    quantity_on_hand INTEGER NOT NULL,
    reorder_level INTEGER NOT NULL,
    sku TEXT NOT NULL,
    unit TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS treatments (
    administration_log JSONB,
    adverse_events JSONB,
    cohort_ids JSONB,
    created_at TIMESTAMPTZ NOT NULL,
    dosage_plan TEXT NOT NULL,
    id UUID NOT NULL,
    name TEXT NOT NULL,
    organism_ids JSONB,
    procedure_id UUID NOT NULL,
    status TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (procedure_id) REFERENCES procedures(id)
);
