-- Code generated by internal/tools/entitymodel/generate. DO NOT EDIT.
-- Dialect: sqlite

CREATE TABLE IF NOT EXISTS facilities (
    access_policy TEXT NOT NULL,
    code TEXT NOT NULL,
    created_at TEXT NOT NULL,
    environment_baselines JSON,
    id TEXT NOT NULL,
    name TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    zone TEXT NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_facilities_nk_1 ON facilities (code);

CREATE TABLE IF NOT EXISTS genotype_markers (
    alleles JSON NOT NULL,
    assay_method TEXT NOT NULL,
    created_at TEXT NOT NULL,
    id TEXT NOT NULL,
    interpretation TEXT NOT NULL,
    locus TEXT NOT NULL,
    name TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    version TEXT NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_genotype_markers_nk_1 ON genotype_markers (name, version);

CREATE TABLE IF NOT EXISTS housing_units (
    capacity INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    environment TEXT NOT NULL,
    facility_id TEXT NOT NULL,
    id TEXT NOT NULL,
    name TEXT NOT NULL,
    state TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (facility_id) REFERENCES facilities(id),
    CHECK (environment IN ('aquatic', 'terrestrial', 'arboreal', 'humid')),
    CHECK (state IN ('quarantine', 'active', 'cleaning', 'decommissioned'))
);
CREATE INDEX IF NOT EXISTS idx_housing_units_facility_id ON housing_units (facility_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_housing_units_nk_1 ON housing_units (facility_id, name);

CREATE TABLE IF NOT EXISTS lines (
    code TEXT NOT NULL,
    created_at TEXT NOT NULL,
    default_attributes JSON,
    deprecated_at TEXT,
    deprecation_reason TEXT,
    description TEXT,
    extension_overrides JSON,
    id TEXT NOT NULL,
    name TEXT NOT NULL,
    origin TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_lines_nk_1 ON lines (code);

CREATE TABLE IF NOT EXISTS lines__genotype_marker_ids (
    line_id TEXT NOT NULL,
    genotype_marker_id TEXT NOT NULL,
    PRIMARY KEY (line_id, genotype_marker_id),
    FOREIGN KEY (line_id) REFERENCES lines(id) ON DELETE CASCADE,
    FOREIGN KEY (genotype_marker_id) REFERENCES genotype_markers(id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_lines__genotype_marker_ids_genotype_marker_id ON lines__genotype_marker_ids (genotype_marker_id);

CREATE TABLE IF NOT EXISTS permits (
    allowed_activities JSON NOT NULL,
    authority TEXT NOT NULL,
    created_at TEXT NOT NULL,
    id TEXT NOT NULL,
    notes TEXT,
    permit_number TEXT NOT NULL,
    status TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    valid_from TEXT NOT NULL,
    valid_until TEXT NOT NULL,
    PRIMARY KEY (id),
    CHECK (status IN ('draft', 'submitted', 'approved', 'on_hold', 'expired', 'archived'))
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_permits_nk_1 ON permits (authority, permit_number);

CREATE TABLE IF NOT EXISTS permits__facility_ids (
    permit_id TEXT NOT NULL,
    facility_id TEXT NOT NULL,
    PRIMARY KEY (permit_id, facility_id),
    FOREIGN KEY (permit_id) REFERENCES permits(id) ON DELETE CASCADE,
    FOREIGN KEY (facility_id) REFERENCES facilities(id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_permits__facility_ids_facility_id ON permits__facility_ids (facility_id);

CREATE TABLE IF NOT EXISTS projects (
    code TEXT NOT NULL,
    created_at TEXT NOT NULL,
    description TEXT,
    id TEXT NOT NULL,
    title TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_projects_nk_1 ON projects (code);

CREATE TABLE IF NOT EXISTS facilities__project_ids (
    facility_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    PRIMARY KEY (facility_id, project_id),
    FOREIGN KEY (facility_id) REFERENCES facilities(id) ON DELETE CASCADE,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_facilities__project_ids_project_id ON facilities__project_ids (project_id);

CREATE TABLE IF NOT EXISTS protocols (
    code TEXT NOT NULL,
    created_at TEXT NOT NULL,
    description TEXT,
    id TEXT NOT NULL,
    max_subjects INTEGER NOT NULL,
    status TEXT NOT NULL,
    title TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (id),
    CHECK (status IN ('draft', 'submitted', 'approved', 'on_hold', 'expired', 'archived'))
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_protocols_nk_1 ON protocols (code);

CREATE TABLE IF NOT EXISTS cohorts (
    created_at TEXT NOT NULL,
    housing_id TEXT,
    id TEXT NOT NULL,
    name TEXT NOT NULL,
    project_id TEXT,
    protocol_id TEXT,
    purpose TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (housing_id) REFERENCES housing_units(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (protocol_id) REFERENCES protocols(id)
);
CREATE INDEX IF NOT EXISTS idx_cohorts_housing_id ON cohorts (housing_id);
CREATE INDEX IF NOT EXISTS idx_cohorts_project_id ON cohorts (project_id);
CREATE INDEX IF NOT EXISTS idx_cohorts_protocol_id ON cohorts (protocol_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_cohorts_nk_1 ON cohorts (project_id, name);

CREATE TABLE IF NOT EXISTS permits__protocol_ids (
    permit_id TEXT NOT NULL,
    protocol_id TEXT NOT NULL,
    PRIMARY KEY (permit_id, protocol_id),
    FOREIGN KEY (permit_id) REFERENCES permits(id) ON DELETE CASCADE,
    FOREIGN KEY (protocol_id) REFERENCES protocols(id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_permits__protocol_ids_protocol_id ON permits__protocol_ids (protocol_id);

CREATE TABLE IF NOT EXISTS procedures (
    cohort_id TEXT,
    created_at TEXT NOT NULL,
    id TEXT NOT NULL,
    name TEXT NOT NULL,
    project_id TEXT,
    protocol_id TEXT NOT NULL,
    scheduled_at TEXT NOT NULL,
    status TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (cohort_id) REFERENCES cohorts(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (protocol_id) REFERENCES protocols(id),
    CHECK (status IN ('scheduled', 'in_progress', 'completed', 'cancelled', 'failed'))
);
CREATE INDEX IF NOT EXISTS idx_procedures_cohort_id ON procedures (cohort_id);
CREATE INDEX IF NOT EXISTS idx_procedures_project_id ON procedures (project_id);
CREATE INDEX IF NOT EXISTS idx_procedures_protocol_id ON procedures (protocol_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_procedures_nk_1 ON procedures (protocol_id, name, scheduled_at);

CREATE TABLE IF NOT EXISTS projects__protocol_ids (
    project_id TEXT NOT NULL,
    protocol_id TEXT NOT NULL,
    PRIMARY KEY (project_id, protocol_id),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (protocol_id) REFERENCES protocols(id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_projects__protocol_ids_protocol_id ON projects__protocol_ids (protocol_id);

CREATE TABLE IF NOT EXISTS strains (
    code TEXT NOT NULL,
    created_at TEXT NOT NULL,
    description TEXT,
    generation TEXT,
    id TEXT NOT NULL,
    line_id TEXT NOT NULL,
    name TEXT NOT NULL,
    retired_at TEXT,
    retirement_reason TEXT,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (line_id) REFERENCES lines(id)
);
CREATE INDEX IF NOT EXISTS idx_strains_line_id ON strains (line_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_strains_nk_1 ON strains (line_id, code);

CREATE TABLE IF NOT EXISTS breeding_units (
    created_at TEXT NOT NULL,
    housing_id TEXT,
    id TEXT NOT NULL,
    line_id TEXT,
    name TEXT NOT NULL,
    pairing_attributes JSON,
    pairing_intent TEXT,
    pairing_notes TEXT,
    protocol_id TEXT,
    strain_id TEXT,
    strategy TEXT NOT NULL,
    target_line_id TEXT,
    target_strain_id TEXT,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (housing_id) REFERENCES housing_units(id),
    FOREIGN KEY (line_id) REFERENCES lines(id),
    FOREIGN KEY (protocol_id) REFERENCES protocols(id),
    FOREIGN KEY (strain_id) REFERENCES strains(id),
    FOREIGN KEY (target_line_id) REFERENCES lines(id),
    FOREIGN KEY (target_strain_id) REFERENCES strains(id)
);
CREATE INDEX IF NOT EXISTS idx_breeding_units_housing_id ON breeding_units (housing_id);
CREATE INDEX IF NOT EXISTS idx_breeding_units_line_id ON breeding_units (line_id);
CREATE INDEX IF NOT EXISTS idx_breeding_units_protocol_id ON breeding_units (protocol_id);
CREATE INDEX IF NOT EXISTS idx_breeding_units_strain_id ON breeding_units (strain_id);
CREATE INDEX IF NOT EXISTS idx_breeding_units_target_line_id ON breeding_units (target_line_id);
CREATE INDEX IF NOT EXISTS idx_breeding_units_target_strain_id ON breeding_units (target_strain_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_breeding_units_nk_1 ON breeding_units (name, line_id);

CREATE TABLE IF NOT EXISTS organisms (
    attributes JSON,
    cohort_id TEXT,
    created_at TEXT NOT NULL,
    housing_id TEXT,
    id TEXT NOT NULL,
    line TEXT NOT NULL,
    line_id TEXT,
    name TEXT NOT NULL,
    project_id TEXT,
    protocol_id TEXT,
    species TEXT NOT NULL,
    stage TEXT NOT NULL,
    strain_id TEXT,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (cohort_id) REFERENCES cohorts(id),
    FOREIGN KEY (housing_id) REFERENCES housing_units(id),
    FOREIGN KEY (line_id) REFERENCES lines(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (protocol_id) REFERENCES protocols(id),
    FOREIGN KEY (strain_id) REFERENCES strains(id),
    CHECK (stage IN ('planned', 'embryo_larva', 'juvenile', 'adult', 'retired', 'deceased'))
);
CREATE INDEX IF NOT EXISTS idx_organisms_cohort_id ON organisms (cohort_id);
CREATE INDEX IF NOT EXISTS idx_organisms_housing_id ON organisms (housing_id);
CREATE INDEX IF NOT EXISTS idx_organisms_line_id ON organisms (line_id);
CREATE INDEX IF NOT EXISTS idx_organisms_project_id ON organisms (project_id);
CREATE INDEX IF NOT EXISTS idx_organisms_protocol_id ON organisms (protocol_id);
CREATE INDEX IF NOT EXISTS idx_organisms_strain_id ON organisms (strain_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_organisms_nk_1 ON organisms (species, line, name);

CREATE TABLE IF NOT EXISTS breeding_units__female_ids (
    breeding_unit_id TEXT NOT NULL,
    organism_id TEXT NOT NULL,
    PRIMARY KEY (breeding_unit_id, organism_id),
    FOREIGN KEY (breeding_unit_id) REFERENCES breeding_units(id) ON DELETE CASCADE,
    FOREIGN KEY (organism_id) REFERENCES organisms(id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_breeding_units__female_ids_organism_id ON breeding_units__female_ids (organism_id);

CREATE TABLE IF NOT EXISTS breeding_units__male_ids (
    breeding_unit_id TEXT NOT NULL,
    organism_id TEXT NOT NULL,
    PRIMARY KEY (breeding_unit_id, organism_id),
    FOREIGN KEY (breeding_unit_id) REFERENCES breeding_units(id) ON DELETE CASCADE,
    FOREIGN KEY (organism_id) REFERENCES organisms(id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_breeding_units__male_ids_organism_id ON breeding_units__male_ids (organism_id);

CREATE TABLE IF NOT EXISTS observations (
    cohort_id TEXT,
    created_at TEXT NOT NULL,
    data JSON,
    id TEXT NOT NULL,
    notes TEXT,
    observer TEXT NOT NULL,
    organism_id TEXT,
    procedure_id TEXT,
    recorded_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (cohort_id) REFERENCES cohorts(id),
    FOREIGN KEY (organism_id) REFERENCES organisms(id),
    FOREIGN KEY (procedure_id) REFERENCES procedures(id)
);
CREATE INDEX IF NOT EXISTS idx_observations_cohort_id ON observations (cohort_id);
CREATE INDEX IF NOT EXISTS idx_observations_organism_id ON observations (organism_id);
CREATE INDEX IF NOT EXISTS idx_observations_procedure_id ON observations (procedure_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_observations_nk_1 ON observations (procedure_id, recorded_at, observer);

CREATE TABLE IF NOT EXISTS organisms__parent_ids (
    organism_id TEXT NOT NULL,
    parent_ids_id TEXT NOT NULL,
    PRIMARY KEY (organism_id, parent_ids_id),
    FOREIGN KEY (organism_id) REFERENCES organisms(id) ON DELETE CASCADE,
    FOREIGN KEY (parent_ids_id) REFERENCES organisms(id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_organisms__parent_ids_parent_ids_id ON organisms__parent_ids (parent_ids_id);

CREATE TABLE IF NOT EXISTS procedures__organism_ids (
    procedure_id TEXT NOT NULL,
    organism_id TEXT NOT NULL,
    PRIMARY KEY (procedure_id, organism_id),
    FOREIGN KEY (procedure_id) REFERENCES procedures(id) ON DELETE CASCADE,
    FOREIGN KEY (organism_id) REFERENCES organisms(id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_procedures__organism_ids_organism_id ON procedures__organism_ids (organism_id);

CREATE TABLE IF NOT EXISTS samples (
    assay_type TEXT NOT NULL,
    attributes JSON,
    chain_of_custody JSON NOT NULL,
    cohort_id TEXT,
    collected_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    facility_id TEXT NOT NULL,
    id TEXT NOT NULL,
    identifier TEXT NOT NULL,
    organism_id TEXT,
    source_type TEXT NOT NULL,
    status TEXT NOT NULL,
    storage_location TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (cohort_id) REFERENCES cohorts(id),
    FOREIGN KEY (facility_id) REFERENCES facilities(id),
    FOREIGN KEY (organism_id) REFERENCES organisms(id),
    CHECK (status IN ('stored', 'in_transit', 'consumed', 'disposed'))
);
CREATE INDEX IF NOT EXISTS idx_samples_cohort_id ON samples (cohort_id);
CREATE INDEX IF NOT EXISTS idx_samples_facility_id ON samples (facility_id);
CREATE INDEX IF NOT EXISTS idx_samples_organism_id ON samples (organism_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_samples_nk_1 ON samples (facility_id, identifier);

CREATE TABLE IF NOT EXISTS strains__genotype_marker_ids (
    strain_id TEXT NOT NULL,
    genotype_marker_id TEXT NOT NULL,
    PRIMARY KEY (strain_id, genotype_marker_id),
    FOREIGN KEY (strain_id) REFERENCES strains(id) ON DELETE CASCADE,
    FOREIGN KEY (genotype_marker_id) REFERENCES genotype_markers(id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_strains__genotype_marker_ids_genotype_marker_id ON strains__genotype_marker_ids (genotype_marker_id);

CREATE TABLE IF NOT EXISTS supply_items (
    attributes JSON,
    created_at TEXT NOT NULL,
    description TEXT,
    expires_at TEXT,
    id TEXT NOT NULL,
    lot_number TEXT,
    name TEXT NOT NULL,
    quantity_on_hand INTEGER NOT NULL,
    reorder_level INTEGER NOT NULL,
    sku TEXT NOT NULL,
    unit TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_supply_items_nk_1 ON supply_items (sku);

CREATE TABLE IF NOT EXISTS projects__supply_item_ids (
    project_id TEXT NOT NULL,
    supply_item_id TEXT NOT NULL,
    PRIMARY KEY (project_id, supply_item_id),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (supply_item_id) REFERENCES supply_items(id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_projects__supply_item_ids_supply_item_id ON projects__supply_item_ids (supply_item_id);

CREATE TABLE IF NOT EXISTS supply_items__facility_ids (
    supply_item_id TEXT NOT NULL,
    facility_id TEXT NOT NULL,
    PRIMARY KEY (supply_item_id, facility_id),
    FOREIGN KEY (supply_item_id) REFERENCES supply_items(id) ON DELETE CASCADE,
    FOREIGN KEY (facility_id) REFERENCES facilities(id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_supply_items__facility_ids_facility_id ON supply_items__facility_ids (facility_id);

CREATE TABLE IF NOT EXISTS treatments (
    administration_log JSON,
    adverse_events JSON,
    created_at TEXT NOT NULL,
    dosage_plan TEXT NOT NULL,
    id TEXT NOT NULL,
    name TEXT NOT NULL,
    procedure_id TEXT NOT NULL,
    status TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (procedure_id) REFERENCES procedures(id),
    CHECK (status IN ('planned', 'in_progress', 'completed', 'flagged'))
);
CREATE INDEX IF NOT EXISTS idx_treatments_procedure_id ON treatments (procedure_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_treatments_nk_1 ON treatments (procedure_id, name);

CREATE TABLE IF NOT EXISTS treatments__cohort_ids (
    treatment_id TEXT NOT NULL,
    cohort_id TEXT NOT NULL,
    PRIMARY KEY (treatment_id, cohort_id),
    FOREIGN KEY (treatment_id) REFERENCES treatments(id) ON DELETE CASCADE,
    FOREIGN KEY (cohort_id) REFERENCES cohorts(id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_treatments__cohort_ids_cohort_id ON treatments__cohort_ids (cohort_id);

CREATE TABLE IF NOT EXISTS treatments__organism_ids (
    treatment_id TEXT NOT NULL,
    organism_id TEXT NOT NULL,
    PRIMARY KEY (treatment_id, organism_id),
    FOREIGN KEY (treatment_id) REFERENCES treatments(id) ON DELETE CASCADE,
    FOREIGN KEY (organism_id) REFERENCES organisms(id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_treatments__organism_ids_organism_id ON treatments__organism_ids (organism_id);
