-- Code generated by internal/tools/entitymodel/generate. DO NOT EDIT.
-- Dialect: sqlite

CREATE TABLE IF NOT EXISTS breeding_units (
    created_at TEXT NOT NULL,
    female_ids JSON,
    housing_id TEXT,
    id TEXT NOT NULL,
    line_id TEXT,
    male_ids JSON,
    name TEXT NOT NULL,
    pairing_attributes JSON,
    pairing_intent TEXT,
    pairing_notes TEXT,
    protocol_id TEXT,
    strain_id TEXT,
    strategy TEXT NOT NULL,
    target_line_id TEXT,
    target_strain_id TEXT,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (housing_id) REFERENCES housing_units(id),
    FOREIGN KEY (line_id) REFERENCES lines(id),
    FOREIGN KEY (protocol_id) REFERENCES protocols(id),
    FOREIGN KEY (strain_id) REFERENCES strains(id),
    FOREIGN KEY (target_line_id) REFERENCES lines(id),
    FOREIGN KEY (target_strain_id) REFERENCES strains(id)
);

CREATE TABLE IF NOT EXISTS cohorts (
    created_at TEXT NOT NULL,
    housing_id TEXT,
    id TEXT NOT NULL,
    name TEXT NOT NULL,
    project_id TEXT,
    protocol_id TEXT,
    purpose TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (housing_id) REFERENCES housing_units(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (protocol_id) REFERENCES protocols(id)
);

CREATE TABLE IF NOT EXISTS facilities (
    access_policy TEXT NOT NULL,
    code TEXT NOT NULL,
    created_at TEXT NOT NULL,
    environment_baselines JSON,
    housing_unit_ids JSON,
    id TEXT NOT NULL,
    name TEXT NOT NULL,
    project_ids JSON,
    updated_at TEXT NOT NULL,
    zone TEXT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS genotype_markers (
    alleles JSON NOT NULL,
    assay_method TEXT NOT NULL,
    created_at TEXT NOT NULL,
    id TEXT NOT NULL,
    interpretation TEXT NOT NULL,
    locus TEXT NOT NULL,
    name TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    version TEXT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS housing_units (
    capacity INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    environment TEXT NOT NULL,
    facility_id TEXT NOT NULL,
    id TEXT NOT NULL,
    name TEXT NOT NULL,
    state TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (facility_id) REFERENCES facilities(id)
);

CREATE TABLE IF NOT EXISTS lines (
    code TEXT NOT NULL,
    created_at TEXT NOT NULL,
    default_attributes JSON,
    deprecated_at TEXT,
    deprecation_reason TEXT,
    description TEXT,
    extension_overrides JSON,
    genotype_marker_ids JSON NOT NULL,
    id TEXT NOT NULL,
    name TEXT NOT NULL,
    origin TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS observations (
    cohort_id TEXT,
    created_at TEXT NOT NULL,
    data JSON,
    id TEXT NOT NULL,
    notes TEXT,
    observer TEXT NOT NULL,
    organism_id TEXT,
    procedure_id TEXT,
    recorded_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (cohort_id) REFERENCES cohorts(id),
    FOREIGN KEY (organism_id) REFERENCES organisms(id),
    FOREIGN KEY (procedure_id) REFERENCES procedures(id)
);

CREATE TABLE IF NOT EXISTS organisms (
    attributes JSON,
    cohort_id TEXT,
    created_at TEXT NOT NULL,
    housing_id TEXT,
    id TEXT NOT NULL,
    line TEXT NOT NULL,
    line_id TEXT,
    name TEXT NOT NULL,
    parent_ids JSON,
    project_id TEXT,
    protocol_id TEXT,
    species TEXT NOT NULL,
    stage TEXT NOT NULL,
    strain_id TEXT,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (cohort_id) REFERENCES cohorts(id),
    FOREIGN KEY (housing_id) REFERENCES housing_units(id),
    FOREIGN KEY (line_id) REFERENCES lines(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (protocol_id) REFERENCES protocols(id),
    FOREIGN KEY (strain_id) REFERENCES strains(id)
);

CREATE TABLE IF NOT EXISTS permits (
    allowed_activities JSON NOT NULL,
    authority TEXT NOT NULL,
    created_at TEXT NOT NULL,
    facility_ids JSON NOT NULL,
    id TEXT NOT NULL,
    notes TEXT,
    permit_number TEXT NOT NULL,
    protocol_ids JSON NOT NULL,
    status TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    valid_from TEXT NOT NULL,
    valid_until TEXT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS procedures (
    cohort_id TEXT,
    created_at TEXT NOT NULL,
    id TEXT NOT NULL,
    name TEXT NOT NULL,
    observation_ids JSON,
    organism_ids JSON,
    project_id TEXT,
    protocol_id TEXT NOT NULL,
    scheduled_at TEXT NOT NULL,
    status TEXT NOT NULL,
    treatment_ids JSON,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (cohort_id) REFERENCES cohorts(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (protocol_id) REFERENCES protocols(id)
);

CREATE TABLE IF NOT EXISTS projects (
    code TEXT NOT NULL,
    created_at TEXT NOT NULL,
    description TEXT,
    facility_ids JSON NOT NULL,
    id TEXT NOT NULL,
    organism_ids JSON,
    procedure_ids JSON,
    protocol_ids JSON,
    supply_item_ids JSON,
    title TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS protocols (
    code TEXT NOT NULL,
    created_at TEXT NOT NULL,
    description TEXT,
    id TEXT NOT NULL,
    max_subjects INTEGER NOT NULL,
    status TEXT NOT NULL,
    title TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS samples (
    assay_type TEXT NOT NULL,
    attributes JSON,
    chain_of_custody JSON NOT NULL,
    cohort_id TEXT,
    collected_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    facility_id TEXT NOT NULL,
    id TEXT NOT NULL,
    identifier TEXT NOT NULL,
    organism_id TEXT,
    source_type TEXT NOT NULL,
    status TEXT NOT NULL,
    storage_location TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (cohort_id) REFERENCES cohorts(id),
    FOREIGN KEY (facility_id) REFERENCES facilities(id),
    FOREIGN KEY (organism_id) REFERENCES organisms(id)
);

CREATE TABLE IF NOT EXISTS strains (
    code TEXT NOT NULL,
    created_at TEXT NOT NULL,
    description TEXT,
    generation TEXT,
    genotype_marker_ids JSON,
    id TEXT NOT NULL,
    line_id TEXT NOT NULL,
    name TEXT NOT NULL,
    retired_at TEXT,
    retirement_reason TEXT,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (line_id) REFERENCES lines(id)
);

CREATE TABLE IF NOT EXISTS supply_items (
    attributes JSON,
    created_at TEXT NOT NULL,
    description TEXT,
    expires_at TEXT,
    facility_ids JSON NOT NULL,
    id TEXT NOT NULL,
    lot_number TEXT,
    name TEXT NOT NULL,
    project_ids JSON NOT NULL,
    quantity_on_hand INTEGER NOT NULL,
    reorder_level INTEGER NOT NULL,
    sku TEXT NOT NULL,
    unit TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS treatments (
    administration_log JSON,
    adverse_events JSON,
    cohort_ids JSON,
    created_at TEXT NOT NULL,
    dosage_plan TEXT NOT NULL,
    id TEXT NOT NULL,
    name TEXT NOT NULL,
    organism_ids JSON,
    procedure_id TEXT NOT NULL,
    status TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (procedure_id) REFERENCES procedures(id)
);
