// Code generated by internal/tools/entitymodel/generate. DO NOT EDIT.
package entitymodel

import "time"

// HousingEnvironment enumerates values for housing_environment.
type HousingEnvironment string

const (
	HousingEnvironmentAquatic     HousingEnvironment = "aquatic"
	HousingEnvironmentTerrestrial HousingEnvironment = "terrestrial"
	HousingEnvironmentArboreal    HousingEnvironment = "arboreal"
	HousingEnvironmentHumid       HousingEnvironment = "humid"
)

// HousingState enumerates values for housing_state.
type HousingState string

const (
	HousingStateQuarantine     HousingState = "quarantine"
	HousingStateActive         HousingState = "active"
	HousingStateCleaning       HousingState = "cleaning"
	HousingStateDecommissioned HousingState = "decommissioned"
)

// LifecycleStage enumerates values for lifecycle_stage.
type LifecycleStage string

const (
	LifecycleStagePlanned     LifecycleStage = "planned"
	LifecycleStageEmbryoLarva LifecycleStage = "embryo_larva"
	LifecycleStageJuvenile    LifecycleStage = "juvenile"
	LifecycleStageAdult       LifecycleStage = "adult"
	LifecycleStageRetired     LifecycleStage = "retired"
	LifecycleStageDeceased    LifecycleStage = "deceased"
)

// PermitStatus enumerates values for permit_status.
type PermitStatus string

const (
	PermitStatusDraft     PermitStatus = "draft"
	PermitStatusSubmitted PermitStatus = "submitted"
	PermitStatusApproved  PermitStatus = "approved"
	PermitStatusOnHold    PermitStatus = "on_hold"
	PermitStatusExpired   PermitStatus = "expired"
	PermitStatusArchived  PermitStatus = "archived"
)

// ProcedureStatus enumerates values for procedure_status.
type ProcedureStatus string

const (
	ProcedureStatusScheduled  ProcedureStatus = "scheduled"
	ProcedureStatusInProgress ProcedureStatus = "in_progress"
	ProcedureStatusCompleted  ProcedureStatus = "completed"
	ProcedureStatusCancelled  ProcedureStatus = "cancelled"
	ProcedureStatusFailed     ProcedureStatus = "failed"
)

// ProtocolStatus enumerates values for protocol_status.
type ProtocolStatus string

const (
	ProtocolStatusDraft     ProtocolStatus = "draft"
	ProtocolStatusSubmitted ProtocolStatus = "submitted"
	ProtocolStatusApproved  ProtocolStatus = "approved"
	ProtocolStatusOnHold    ProtocolStatus = "on_hold"
	ProtocolStatusExpired   ProtocolStatus = "expired"
	ProtocolStatusArchived  ProtocolStatus = "archived"
)

// SampleStatus enumerates values for sample_status.
type SampleStatus string

const (
	SampleStatusStored    SampleStatus = "stored"
	SampleStatusInTransit SampleStatus = "in_transit"
	SampleStatusConsumed  SampleStatus = "consumed"
	SampleStatusDisposed  SampleStatus = "disposed"
)

// TreatmentStatus enumerates values for treatment_status.
type TreatmentStatus string

const (
	TreatmentStatusPlanned    TreatmentStatus = "planned"
	TreatmentStatusInProgress TreatmentStatus = "in_progress"
	TreatmentStatusCompleted  TreatmentStatus = "completed"
	TreatmentStatusFlagged    TreatmentStatus = "flagged"
)

// SampleCustodyEvent is generated from entity-model.json definitions.
type SampleCustodyEvent struct {
	Actor     string    `json:"actor"`
	Location  string    `json:"location"`
	Notes     *string   `json:"notes,omitempty"`
	Timestamp time.Time `json:"timestamp"`
}

// BreedingUnit is generated from entity-model.json entities.
type BreedingUnit struct {
	CreatedAt         time.Time      `json:"created_at"`
	FemaleIDs         []string       `json:"female_ids,omitempty"`
	HousingID         *string        `json:"housing_id,omitempty"`
	ID                string         `json:"id"`
	LineID            *string        `json:"line_id,omitempty"`
	MaleIDs           []string       `json:"male_ids,omitempty"`
	Name              string         `json:"name"`
	PairingAttributes map[string]any `json:"pairing_attributes,omitempty"`
	PairingIntent     *string        `json:"pairing_intent,omitempty"`
	PairingNotes      *string        `json:"pairing_notes,omitempty"`
	ProtocolID        *string        `json:"protocol_id,omitempty"`
	StrainID          *string        `json:"strain_id,omitempty"`
	Strategy          string         `json:"strategy"`
	TargetLineID      *string        `json:"target_line_id,omitempty"`
	TargetStrainID    *string        `json:"target_strain_id,omitempty"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

// Cohort is generated from entity-model.json entities.
type Cohort struct {
	CreatedAt  time.Time `json:"created_at"`
	HousingID  *string   `json:"housing_id,omitempty"`
	ID         string    `json:"id"`
	Name       string    `json:"name"`
	ProjectID  *string   `json:"project_id,omitempty"`
	ProtocolID *string   `json:"protocol_id,omitempty"`
	Purpose    string    `json:"purpose"`
	UpdatedAt  time.Time `json:"updated_at"`
}

// Facility is generated from entity-model.json entities.
type Facility struct {
	AccessPolicy         string         `json:"access_policy"`
	Code                 string         `json:"code"`
	CreatedAt            time.Time      `json:"created_at"`
	EnvironmentBaselines map[string]any `json:"environment_baselines,omitempty"`
	HousingUnitIDs       []string       `json:"housing_unit_ids,omitempty"`
	ID                   string         `json:"id"`
	Name                 string         `json:"name"`
	ProjectIDs           []string       `json:"project_ids,omitempty"`
	UpdatedAt            time.Time      `json:"updated_at"`
	Zone                 string         `json:"zone"`
}

// GenotypeMarker is generated from entity-model.json entities.
type GenotypeMarker struct {
	Alleles        []string  `json:"alleles"`
	AssayMethod    string    `json:"assay_method"`
	CreatedAt      time.Time `json:"created_at"`
	ID             string    `json:"id"`
	Interpretation string    `json:"interpretation"`
	Locus          string    `json:"locus"`
	Name           string    `json:"name"`
	UpdatedAt      time.Time `json:"updated_at"`
	Version        string    `json:"version"`
}

// HousingUnit is generated from entity-model.json entities.
type HousingUnit struct {
	Capacity    int                `json:"capacity"`
	CreatedAt   time.Time          `json:"created_at"`
	Environment HousingEnvironment `json:"environment"`
	FacilityID  string             `json:"facility_id"`
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	State       HousingState       `json:"state"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// Line is generated from entity-model.json entities.
type Line struct {
	Code               string         `json:"code"`
	CreatedAt          time.Time      `json:"created_at"`
	DefaultAttributes  map[string]any `json:"default_attributes,omitempty"`
	DeprecatedAt       *time.Time     `json:"deprecated_at,omitempty"`
	DeprecationReason  *string        `json:"deprecation_reason,omitempty"`
	Description        *string        `json:"description,omitempty"`
	ExtensionOverrides map[string]any `json:"extension_overrides,omitempty"`
	GenotypeMarkerIDs  []string       `json:"genotype_marker_ids"`
	ID                 string         `json:"id"`
	Name               string         `json:"name"`
	Origin             string         `json:"origin"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

// Observation is generated from entity-model.json entities.
type Observation struct {
	CohortID    *string        `json:"cohort_id,omitempty"`
	CreatedAt   time.Time      `json:"created_at"`
	Data        map[string]any `json:"data,omitempty"`
	ID          string         `json:"id"`
	Notes       *string        `json:"notes,omitempty"`
	Observer    string         `json:"observer"`
	OrganismID  *string        `json:"organism_id,omitempty"`
	ProcedureID *string        `json:"procedure_id,omitempty"`
	RecordedAt  time.Time      `json:"recorded_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

// Organism is generated from entity-model.json entities.
type Organism struct {
	Attributes map[string]any `json:"attributes,omitempty"`
	CohortID   *string        `json:"cohort_id,omitempty"`
	CreatedAt  time.Time      `json:"created_at"`
	HousingID  *string        `json:"housing_id,omitempty"`
	ID         string         `json:"id"`
	Line       string         `json:"line"`
	LineID     *string        `json:"line_id,omitempty"`
	Name       string         `json:"name"`
	ParentIDs  []string       `json:"parent_ids,omitempty"`
	ProjectID  *string        `json:"project_id,omitempty"`
	ProtocolID *string        `json:"protocol_id,omitempty"`
	Species    string         `json:"species"`
	Stage      LifecycleStage `json:"stage"`
	StrainID   *string        `json:"strain_id,omitempty"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

// Permit is generated from entity-model.json entities.
type Permit struct {
	AllowedActivities []string     `json:"allowed_activities"`
	Authority         string       `json:"authority"`
	CreatedAt         time.Time    `json:"created_at"`
	FacilityIDs       []string     `json:"facility_ids"`
	ID                string       `json:"id"`
	Notes             *string      `json:"notes,omitempty"`
	PermitNumber      string       `json:"permit_number"`
	ProtocolIDs       []string     `json:"protocol_ids"`
	Status            PermitStatus `json:"status"`
	UpdatedAt         time.Time    `json:"updated_at"`
	ValidFrom         time.Time    `json:"valid_from"`
	ValidUntil        time.Time    `json:"valid_until"`
}

// Procedure is generated from entity-model.json entities.
type Procedure struct {
	CohortID       *string         `json:"cohort_id,omitempty"`
	CreatedAt      time.Time       `json:"created_at"`
	ID             string          `json:"id"`
	Name           string          `json:"name"`
	ObservationIDs []string        `json:"observation_ids,omitempty"`
	OrganismIDs    []string        `json:"organism_ids,omitempty"`
	ProjectID      *string         `json:"project_id,omitempty"`
	ProtocolID     string          `json:"protocol_id"`
	ScheduledAt    time.Time       `json:"scheduled_at"`
	Status         ProcedureStatus `json:"status"`
	TreatmentIDs   []string        `json:"treatment_ids,omitempty"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

// Project is generated from entity-model.json entities.
type Project struct {
	Code          string    `json:"code"`
	CreatedAt     time.Time `json:"created_at"`
	Description   *string   `json:"description,omitempty"`
	FacilityIDs   []string  `json:"facility_ids"`
	ID            string    `json:"id"`
	OrganismIDs   []string  `json:"organism_ids,omitempty"`
	ProcedureIDs  []string  `json:"procedure_ids,omitempty"`
	ProtocolIDs   []string  `json:"protocol_ids,omitempty"`
	SupplyItemIDs []string  `json:"supply_item_ids,omitempty"`
	Title         string    `json:"title"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// Protocol is generated from entity-model.json entities.
type Protocol struct {
	Code        string         `json:"code"`
	CreatedAt   time.Time      `json:"created_at"`
	Description *string        `json:"description,omitempty"`
	ID          string         `json:"id"`
	MaxSubjects int            `json:"max_subjects"`
	Status      ProtocolStatus `json:"status"`
	Title       string         `json:"title"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

// Sample is generated from entity-model.json entities.
type Sample struct {
	AssayType       string               `json:"assay_type"`
	Attributes      map[string]any       `json:"attributes,omitempty"`
	ChainOfCustody  []SampleCustodyEvent `json:"chain_of_custody"`
	CohortID        *string              `json:"cohort_id,omitempty"`
	CollectedAt     time.Time            `json:"collected_at"`
	CreatedAt       time.Time            `json:"created_at"`
	FacilityID      string               `json:"facility_id"`
	ID              string               `json:"id"`
	Identifier      string               `json:"identifier"`
	OrganismID      *string              `json:"organism_id,omitempty"`
	SourceType      string               `json:"source_type"`
	Status          SampleStatus         `json:"status"`
	StorageLocation string               `json:"storage_location"`
	UpdatedAt       time.Time            `json:"updated_at"`
}

// Strain is generated from entity-model.json entities.
type Strain struct {
	Code              string     `json:"code"`
	CreatedAt         time.Time  `json:"created_at"`
	Description       *string    `json:"description,omitempty"`
	Generation        *string    `json:"generation,omitempty"`
	GenotypeMarkerIDs []string   `json:"genotype_marker_ids,omitempty"`
	ID                string     `json:"id"`
	LineID            string     `json:"line_id"`
	Name              string     `json:"name"`
	RetiredAt         *time.Time `json:"retired_at,omitempty"`
	RetirementReason  *string    `json:"retirement_reason,omitempty"`
	UpdatedAt         time.Time  `json:"updated_at"`
}

// SupplyItem is generated from entity-model.json entities.
type SupplyItem struct {
	Attributes     map[string]any `json:"attributes,omitempty"`
	CreatedAt      time.Time      `json:"created_at"`
	Description    *string        `json:"description,omitempty"`
	ExpiresAt      *time.Time     `json:"expires_at,omitempty"`
	FacilityIDs    []string       `json:"facility_ids"`
	ID             string         `json:"id"`
	LotNumber      *string        `json:"lot_number,omitempty"`
	Name           string         `json:"name"`
	ProjectIDs     []string       `json:"project_ids"`
	QuantityOnHand int            `json:"quantity_on_hand"`
	ReorderLevel   int            `json:"reorder_level"`
	SKU            string         `json:"sku"`
	Unit           string         `json:"unit"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

// Treatment is generated from entity-model.json entities.
type Treatment struct {
	AdministrationLog []string        `json:"administration_log,omitempty"`
	AdverseEvents     []string        `json:"adverse_events,omitempty"`
	CohortIDs         []string        `json:"cohort_ids,omitempty"`
	CreatedAt         time.Time       `json:"created_at"`
	DosagePlan        string          `json:"dosage_plan"`
	ID                string          `json:"id"`
	Name              string          `json:"name"`
	OrganismIDs       []string        `json:"organism_ids,omitempty"`
	ProcedureID       string          `json:"procedure_id"`
	Status            TreatmentStatus `json:"status"`
	UpdatedAt         time.Time       `json:"updated_at"`
}
