// Code generated by internal/tools/entitymodel/generate. DO NOT EDIT.
package pluginapi

const (
	stagePlanned  LifecycleStage = "planned"
	stageLarva    LifecycleStage = "embryo_larva"
	stageJuvenile LifecycleStage = "juvenile"
	stageAdult    LifecycleStage = "adult"
	stageRetired  LifecycleStage = "retired"
	stageDeceased LifecycleStage = "deceased"
)

const (
	housingStateQuarantine     HousingState = "quarantine"
	housingStateActive         HousingState = "active"
	housingStateCleaning       HousingState = "cleaning"
	housingStateDecommissioned HousingState = "decommissioned"
)

const (
	environmentTypeAquatic     = "aquatic"
	environmentTypeTerrestrial = "terrestrial"
	environmentTypeArboreal    = "arboreal"
	environmentTypeHumid       = "humid"
)

const (
	protocolStatusDraft     = "draft"
	protocolStatusSubmitted = "submitted"
	protocolStatusApproved  = "approved"
	protocolStatusOnHold    = "on_hold"
	protocolStatusExpired   = "expired"
	protocolStatusArchived  = "archived"
)

const (
	permitStatusDraft     = "draft"
	permitStatusSubmitted = "submitted"
	permitStatusApproved  = "approved"
	permitStatusOnHold    = "on_hold"
	permitStatusExpired   = "expired"
	permitStatusArchived  = "archived"
)

const (
	sampleStatusStored    = "stored"
	sampleStatusInTransit = "in_transit"
	sampleStatusConsumed  = "consumed"
	sampleStatusDisposed  = "disposed"
)

const (
	treatmentStatusPlanned    = "planned"
	treatmentStatusInProgress = "in_progress"
	treatmentStatusCompleted  = "completed"
	treatmentStatusFlagged    = "flagged"
)

const (
	procedureStatusScheduled  = "scheduled"
	procedureStatusInProgress = "in_progress"
	procedureStatusCompleted  = "completed"
	procedureStatusCancelled  = "cancelled"
	procedureStatusFailed     = "failed"
)
