package main

import (
	"fmt"
	"go/format"
	"strings"
)

type extensionEnumConfig struct {
	EnumKey         string
	TypeName        string
	Prefix          string
	PackagePrefixes map[string]string
	CustomNames     map[string]string
}

var extensionEnumConfigs = []extensionEnumConfig{
	{EnumKey: "lifecycle_stage", TypeName: "LifecycleStage", Prefix: "stage", CustomNames: map[string]string{"embryo_larva": "stageLarva"}},
	{EnumKey: "housing_state", TypeName: "HousingState", Prefix: "housingState"},
	{EnumKey: "housing_environment", Prefix: "environmentType"},
	{
		EnumKey: "protocol_status",
		Prefix:  "protocolStatus",
		PackagePrefixes: map[string]string{
			"datasetapi": "datasetProtocolStatus",
		},
	},
	{
		EnumKey: "permit_status",
		Prefix:  "permitStatus",
		PackagePrefixes: map[string]string{
			"datasetapi": "datasetPermitStatus",
		},
	},
	{
		EnumKey: "sample_status",
		Prefix:  "sampleStatus",
		PackagePrefixes: map[string]string{
			"datasetapi": "datasetSampleStatus",
		},
	},
	{
		EnumKey: "treatment_status",
		Prefix:  "treatmentStatus",
		PackagePrefixes: map[string]string{
			"datasetapi": "datasetTreatmentStatus",
		},
	},
	{EnumKey: "procedure_status", Prefix: "procedureStatus"},
}

func generateExtensionConstants(doc schemaDoc, pkg string) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by internal/tools/entitymodel/generate. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	for _, cfg := range extensionEnumConfigs {
		enum, ok := doc.Enums[cfg.EnumKey]
		if !ok {
			return nil, fmt.Errorf("enum %s not found in schema", cfg.EnumKey)
		}
		if len(enum.Values) == 0 {
			continue
		}
		b.WriteString("const (\n")
		for _, value := range enum.Values {
			if override, ok := cfg.CustomNames[value]; ok {
				name := override
				if cfg.TypeName != "" {
					fmt.Fprintf(&b, "\t%s %s = \"%s\"\n", name, cfg.TypeName, value)
					continue
				}
				fmt.Fprintf(&b, "\t%s = \"%s\"\n", name, value)
				continue
			}
			prefix := cfg.Prefix
			if pkgPrefix, ok := cfg.PackagePrefixes[pkg]; ok {
				prefix = pkgPrefix
			}
			name := prefix + toCamel(value)
			if cfg.TypeName != "" {
				fmt.Fprintf(&b, "\t%s %s = \"%s\"\n", name, cfg.TypeName, value)
				continue
			}
			fmt.Fprintf(&b, "\t%s = \"%s\"\n", name, value)
		}
		b.WriteString(")\n\n")
	}

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("format extension constants: %w", err)
	}
	return formatted, nil
}
